name: repro

on:
  push:
  pull_request:

jobs:
  repro:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set env
        shell: bash
        run: |
          echo "tag=${{ matrix.version }}" >> $GITHUB_ENV
          echo "The tag to update is $tag"
      - name: read env
        shell: bash
        run: |
          echo "The tag to update is $tag"
